### Obtener todos los cursos
GET http://localhost:9999/api/v1/courses/all
Accept: application/json

### Obtener un curso por ID
GET http://localhost:9999/api/v1/courses/2
Accept: application/json

### Crear un nuevo curso
POST http://localhost:9999/api/v1/courses/create
Content-Type: application/json
Accept: application/json

{
  "title": "Introducción a Java",
  "image": "https://miro.medium.com/v2/resize:fit:1400/0*rYlqvld5ocBguLMw.png",
  "description": "Curso básico de programación en Java.",
  "duration" : 45,
  "rating": 4.5,
  "abilities": "Conocimientos básicos de programación.",
  "avaibalable": true,
  "categoryCourseId": 1,
  "teacherUserId": 2
}

### Crear un nuevo curso
POST http://localhost:9999/api/v1/courses/create
Content-Type: application/json
Accept: application/json

{
  "title": "Introducción a Musica",
  "image": "https://capian.co/assets/images/uploads/blog/ckia8-music-lockdown-1fa0fb8b.jpg",
  "description": "Curso básico de Musica.",
  "duration" : 90,
  "rating": 3.5,
  "abilities": "Conocimientos básicos;leer musica;evaluacion de oido",
  "avaibalable": true,
  "categoryCourseId": 5,
  "teacherUserId": 2
}

### Actualizar un curso por ID
PUT http://localhost:9999/api/v1/courses/{id}
Content-Type: application/json
Accept: application/json

{
  "title": "Java para Desarrolladores",
  "description": "Curso avanzado de programación en Java.",
  "categoryId": 1,
  "duration": 45
}

### Eliminar un curso por ID
DELETE http://localhost:9999/api/v1/courses/{id}
Accept: application/json

### obtener un curso por duracion
GET http://localhost:9999/api/v1/courses/duration/45
Accept: application/json

### obtener un curso por rating
GET http://localhost:9999/api/v1/courses/rating/3.5
Accept: application/json
