### Registro de un nuevo usuario (Sign-up)
POST http://localhost:9999/api/v1/user/signup
Content-Type: application/json
Accept: application/json

{
  "firstName": "Marco",
  "lastName": "Reynolds",
  "email": "etedaeamerinst090@gmail.com",
  "username": "marcoreynolds",
  "password": "Lolsito_12345",
  "role": 1,
  "verification": true,
  "activation": false,
  "dateJoin": "2024-09-14"
}

### Inicio de sesión (Log-in)
POST http://localhost:9999/api/v1/user/login
Content-Type: application/json
Accept: application/json

{
  "identifier": "marcoreynolds",
  "password": "Lolsito_12345"
}

### Registro de un nuevo usuario (Sign-up)
POST http://localhost:9999/api/v1/user/signup
Content-Type: application/json
Accept: application/json

{
  "firstName": "Marco F",
  "lastName": "Reynolds G",
  "email": "marquitofrg@gmail.com",
  "username": "marcor",
  "password": "Lolsito1502",
  "role": 2,
  "verification": false,
  "activation": false,
  "dateJoin": "2024-09-14"
}

### Inicio de sesión (Log-in)
POST http://localhost:9999/api/v1/user/login
Content-Type: application/json
Accept: application/json

{
  "identifier": "marquitofrg@gmail.com",
  "password": "Lolsito1502"
}

### Obtener todos los usuarios
GET http://localhost:9999/api/v1/user/all
Accept: application/json

### Obtener un usuario por ID
GET http://localhost:9999/api/v1/user/1
Accept: application/json

### Obtener usuarios por rol
GET http://localhost:9999/api/v1/user/role/1
Accept: application/json

### Actualizar un usuario por ID
PUT http://localhost:9999/api/v1/user/1
Content-Type: application/json
Accept: application/json

{
  "firstName": "Marco Fernando",
  "lastName": "Reynolds Gamez",
  "email": "marco.reynolds@ucb.edu.bo",
  "password": "lolsito101",
  "verification": false
}

### Eliminar un usuario por ID
DELETE http://localhost:9999/api/v1/user/2
Accept: application/json

### Enviar Correo
POST http://localhost:9999/api/v1/mail/send/luanhuancam@gmail.com
Content-Type: application/json
Accept: application/json

{
  "subject": "Código de Verificación en Dos Pasos",
  "message": "Hola Mundo"
}

